### PR TITLE
lyrics: implement currently playing song lyrics feature

### PR DESCRIPTION
**Pull request by Blacksuan19**
gets song name and artist from LastFM module

### CODE REVIEW

**Comment by adekmaulana** [comment]
thank you!
i cleaned up here https://github.com/adekmaulana/ProjectBish/commit/0389235af08839934feb0fc3ec83141e7fd12487 so the cmd doesn't too long

**Comment by gudmeong** [comment]
@adekmaulana Yaudah iya

**Comment by Blacksuan19** [comment]
Noice :ok_hand:

**Comment by ghost** [comment]
@Blacksuan19 Hmm

**Pull request merged**
